version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      
  pre_build:
    commands:
      - echo Installing npm dependencies...
      - npm ci
      
  build:
    commands:
      - echo Building Next.js application...
      - npm run build
      - echo Build completed successfully
      
  post_build:
    commands:
      - echo Build phase completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: out
  
cache:
  paths:
    - node_modules/**/*